name: Prepare Release

on:
  pull_request:
    types:
    - closed
    branches:
    - develop

jobs:
  tag-and-release:
    # Run only after release PR branch is merged
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'updates/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop

      - name: Get canonical version
        id: version
        run: echo "version=$(cat pubspec.yaml | yq -r '.version')" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Release ${{ steps.version.outputs.version }}"
          committer: "Alchemer Mobile Team <sdks@apptentive.com>"
          branch: "releases/${{ steps.version.outputs.version }}"
          base: main
          title: "Release ${{ steps.version.outputs.version }}"
          body-path: .scripts/changes.md